#ifndef MAIN_H
#define MAIN_H

#include "ets_sys.h"
#include "user_interface.h"

/* flash size dependant parameters that are defined by Make ******************/
#ifndef TARGET_FLASH_SIZE_HEX
#define TARGET_FLASH_SIZE_HEX 0x0
#endif /* TARGET_FLASH_SIZE_HEX */
#ifndef SPI_FLASH_SIZE_MAP
#define SPI_FLASH_SIZE_MAP 0
#endif /* SPI_FLASH_SIZE_MAP */
#ifndef SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR
#define SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR 0x0
#endif /* SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR */
#ifndef SYSTEM_PARTITION_PHY_DATA_ADDR
#define SYSTEM_PARTITION_PHY_DATA_ADDR 0x0
#endif /* SYSTEM_PARTITION_PHY_DATA_ADDR */
#ifndef SYSTEM_PARTITION_RF_CAL_ADDR
#define SYSTEM_PARTITION_RF_CAL_ADDR 0x0
#endif /* SYSTEM_PARTITION_RF_CAL_ADDR */

#define EAGLE_FLASH_BIN_ADDR (SYSTEM_PARTITION_CUSTOMER_BEGIN + 1)
#define EAGLE_IROM0TEXT_BIN_ADDR (SYSTEM_PARTITION_CUSTOMER_BEGIN + 2)

static const partition_item_t partition_table[] = {
    {EAGLE_FLASH_BIN_ADDR, 0x00000, 0x10000},
    {EAGLE_IROM0TEXT_BIN_ADDR, 0x10000, 0xC0000},
    {SYSTEM_PARTITION_RF_CAL, SYSTEM_PARTITION_RF_CAL_ADDR, 0x1000},
    {SYSTEM_PARTITION_PHY_DATA, SYSTEM_PARTITION_PHY_DATA_ADDR, 0x1000},
    {SYSTEM_PARTITION_SYSTEM_PARAMETER, SYSTEM_PARTITION_SYSTEM_PARAMETER_ADDR,
     0x3000},
};

#endif /* MAIN_H */
